# Use the existing JavaScript Node image as a base
FROM mcr.microsoft.com/devcontainers/javascript-node:18-bullseye

# Install Twilio CLI
RUN curl -fsSL https://raw.githubusercontent.com/twilio/twilio-cli/main/install.sh | bash
